alternate: 湖心小筑

# Assets
statics: / #//cdn.jsdelivr.net/gh/amehime/shoka@latest/ 

open_graph:
  #twitter_id:
  #google_plus:
  #fb_admins:
  #fb_app_id:

menu:
  home: / || home
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  friends: /friends/ || heart

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/smile-lxy || github || "#191717"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/ || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/ || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home || cloud-music || "#e60026"
  #weibo: https://weibo.com/ || weibo || "#ea716e"
  #about: https://about.me/ || address-card || "#3b5998"
  #email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2020
  count: true

post:
  count: true


# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Comments

# bgm
audio:
  - title: 日本
    list:
      - https://music.163.com/playlist?id=2109140602
  - title: 中国
    list:
      - https://music.163.com/playlist?id=2107965092

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: true

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------


# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true

darkmode: true # true

auto_scroll: # false
